sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "6"
  - "4"
before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
notifications:
  email:
    - anandsuresh@gmail.com
